# Generated by Django 4.2.9 on 2024-02-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualdevelopmentplan',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='template',
            name='pub_date',
        ),
    ]
