# Generated by Django 5.0.1 on 2024-01-19 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualdevelopmentplan',
            name='task',
        ),
        migrations.AddField(
            model_name='individualdevelopmentplan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'открыт'), (1, 'в работе'), (2, 'выполнен'), (3, 'отменен')], default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='task',
            name='ipr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='ipr.individualdevelopmentplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='goal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'открыт'), (1, 'в работе'), (2, 'выполнен'), (3, 'отменен')], verbose_name='status'),
        ),
    ]
