# Generated by Django 5.0.1 on 2024-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipr', '0002_remove_individualdevelopmentplan_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'открыт'), (1, 'в работе'), (2, 'выполнен'), (3, 'отменен')], verbose_name='status'),
        ),
    ]
