# Generated by Django 4.2.9 on 2024-02-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipr', '0002_alter_comment_author_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('linkURL', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('department', models.CharField(choices=[('art', 'Дизайн'), ('QA', 'QA'), ('BA', 'BA'), ('SA', 'SA')], max_length=12, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['department'],
            },
        ),
    ]
