version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: anastasia289/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: anastasia289/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: anastasia289/foodgram_infra
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend


# docker compose exec backend cp -r /app/backend_static/. /backend_static/