# Generated by Django 4.2.9 on 2024-01-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatestask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title'], 'verbose_name': 'отдел/направление', 'verbose_name_plural': 'отдел/направление'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['department'], 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
    ]
