# Generated by Django 4.2.9 on 2024-02-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatestask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(choices=[('frontend', 'Фронтенд'), ('backend', 'Бэкенд'), ('design', 'Дизайн'), ('QA', 'QA'), ('BA', 'BA'), ('SA', 'SA')], max_length=100, verbose_name='title'),
        ),
    ]
