# Generated by Django 5.0.1 on 2024-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatestask', '0002_alter_department_options_alter_template_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title'], 'verbose_name': 'направление', 'verbose_name_plural': 'направления'},
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Дизайн'), (1, 'QA'), (2, 'BA'), (3, 'SA')], verbose_name='title'),
        ),
    ]
